language: ruby

rvm:
  - 2.4.4
  - 2.5.1
  - 2.6.3

notifications:
  email:
    on_success: change
    on_failure: always

gemfile:
  - Gemfile
  - Gemfile.aws-sdk-core-v2

env:
  - SPEC_ALL=true

script: bundle exec rspec spec

before_install:
  - gem install bundler -v '< 2'

after_success:
  - bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: 7709fd21981bb9d2658647a66d959415a1029a83f1c199573828797944f26c52
